# -*- coding: utf-8 -*-
"""Copy of intropython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M7QvOBgsfoUDpwhO0kVEAMox0h3JArtj
"""

name = input("Enter your Name: ")
marks = int(input("Enter your Mark: "))
print("I am", name, "and my mark is: ", marks)

firstnum = int(input("Enter First Number: "))
Secondnum = int(input("Enter Second Number: "))

arithmetics = firstnum + Secondnum

print("Additional is", arithmetics)
